### ISSUE TITLE
Specify summary treatment

### ISSUE THREAD

**Issue by sbddesign** [atlantabitdevs/bitdevs-upgrade#20]
Basically, the AI scrapper currently scraps every link in the page. We may not always want this. For example, I don't need the meetup.com page or link to afterparty bar getting summarized. So we need a way to differentiate them.

- Opt-in links to be summarized?
- Opt-out links to be summarized?
- Other ways to config?

**Comment by niteshbalusu11** [comment]
@sbddesign it only starts scraping from ### Mailing Lists 

Everything above that ignored.

**Comment by bnonni** [comment]
v2.0 Requirements / Context
- [ ] need a way to allow organizers to easily have summarizer ignore links

Solution
- [ ] Any link surrounded by ignore comments gets excluded

e.g.
```markdown
<!-- @summarizer end ignore -->
## Announcements
Content
Content
Content
<!-- @summarizer end ignore -->
```

**Comment by sbddesign** [comment]
For MVP, we need to do it like so:

```markdown
<h4> <a href="https://lists.linuxfoundation.org/pipermail/bitcoin-dev" data-no-summary>bitcoin-dev</a> </h4>

[On the experiment of the Bitcoin Contracting Primitives WG and marking this community process "up for grabs"](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-July/021786.html)

[Blinded 2-party Musig2](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-July/021792.html)
```
  
In the above example, the `<a>` hyperlink should **not** be summarized and the two markdown hyperlinks **should** be summarized.

**Comment by niteshbalusu11** [comment]
https://github.com/atlantabitdevs/bitdevs-upgrade/commit/c0bc98ecff3cb4e130415e99aa1c273d9534dde9
