### ISSUE TITLE
Setup rendering of individuals pages

### ISSUE THREAD

**Issue by sbddesign** [atlantabitdevs/bitdevs-upgrade#29]
Create a NextJS template such that any markdown file in `content/pages` (e.g. `mypage.md`) is accessible at `https://site.com/mypage` and has the markdown content parsed and rendered.

**Comment by jordan-bravo** [comment]
I hit a blocker.  I'm working on `app/page/[id]/page.tsx`.  In the browser, going to `/page/about` leads to the error:
```typescript
 error TypeError: Cannot read properties of undefined (reading 'body')
    at Posts (./app/page/[id]/page.tsx:63:28)
```

All updates have been pushed to branch `29-pages-from-markdown`.

**Comment by jordan-bravo** [comment]
This has been completed with PR #48
