### ISSUE TITLE
Clicking the title of posts/events should take you to that page

### ISSUE THREAD

**Issue by jordan-bravo** [atlantabitdevs/bitdevs-upgrade#35]
For example, clicking "Really Cool Topic Title" should take you to `/posts/really-cool`.

**Comment by sbddesign** [comment]
Done

**Comment by jordan-bravo** [comment]
Oh no, I just finished working on this too!

**Comment by jordan-bravo** [comment]
After looking at `main`, it looks like my PR is still relevant: #36
