### ISSUE TITLE
Static Site Gen from JSON Files: Individual pages per event

### ISSUE THREAD

**Issue by jordan-bravo** [atlantabitdevs/bitdevs-upgrade#8]
- [ ] Each post should have a page generated with a URL path for each meetup event based on its file name.
- [ ] Each generated meetup page should render the markdown content of that file.

**Comment by sbddesign** [comment]
@jordan-bravo a little confused by wording of 2nd bullet point. Are you talking about the listing that shows all the meetups? e.g. what you accomplished with PR #9 ?

**Comment by jordan-bravo** [comment]
No, my understanding was that in addition to showing a list of all the meetups' titles/dates, we also want each of those titles to be clickable so that when clicked, it opens up a page that displays the _contents_ of each markdown file.  

This ticket is to build the functionality so that the contents of the markdown file (the actual body of the file) is processed and a new page is generated for each file that displays those contents.

**Comment by sbddesign** [comment]
Props to @gratten for finding a fix for this using the Content Layer library and @jordan-bravo and @bnonni for the prior art
