### ISSUE TITLE
In the ai folder, there is no information about where meetup folder comes from or what it is

### ISSUE THREAD

**Issue by austenjt** [atlantabitdevs/bitdevs-upgrade#81]
I'm a user that forked and I am trying to run a copy of the site so I can make a similar site.

In the ai folder, there is no information about where meetup folder comes from or what it is.   All I know is that it's an object that contains an `ai array`.

When I try to `yarn start` the `ai` folder,  it says:

```
error TS2307: Cannot find module './meetup' or its corresponding type declarations.
9 import { meetup } from './meetup'
```

How do I resolve?

Also, do you have any info about how to setup the Github actions?   Normally a site can be build statically, with `next export` but this site cant be built that way.  So, therefore,  knowing how you setup your Github actions might help me understand how you build & deploy without using `next export`.

**Comment by austenjt** [comment]
Hmm.  Turns out the README misled me, and running yarn commands from the `./ai` folder is not intended.   Instead,  trying to build from root of the project with `yarn` instead of `npm run` commands, seems to be the trick.    README was not clear but I think I figured it out.  Looking back at the README, it did give a hint.

**Comment by austenjt** [comment]
Got mine working here: https://github.com/Portland-Bit-Devs/portland-bitdevs-upgrade

See: https://github.com/Portland-Bit-Devs/portland-bitdevs-upgrade/blob/main/Dockerfile

**Comment by sbddesign** [comment]
@austenjt glad you got it working! You are not the first one to raise awareness to this. I actually had a PR open to fix the readme, I just left it open for feedback. Does this readme in #79 look better to you?

- If YES, could you review + approve it?
- If NO, could you let me know how to improve it?

**Comment by austenjt** [comment]
hey Stephen,

Our website did work for a while during January, but last time I checked in
February, I can no longer get it to render the markdown.

I was wondering if you could pull a copy of the repo and tell me what you
think the issue might be?

I am certain that my .env OPENAI_API_KEY is correct.

I am just stuck.   I am a NPM expert but Yarn also throws me off.  The
configuration is a bit different than I usually use on Angular projects.

-Jon

**Comment by austenjt** [comment]
The repo is at:
https://github.com/Portland-Bit-Devs/portland-bitdevs-upgrade
